package cl.bicevida.view.planillacaja.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630262
 * 2017-09-28T11:36:19.786-03:00
 * Generated source version: 3.1.5.redhat-630262
 * 
 */
@WebService(targetNamespace = "http://ws.planillacaja.view.bicevida.cl/", name = "PlanillaCajaWS")
@XmlSeeAlso({ObjectFactory.class})
public interface PlanillaCajaWS {

    @WebMethod
    @Action(input = "http://ws.planillacaja.view.bicevida.cl/PlanillaCajaWS/getUrlPDFRequest", output = "http://ws.planillacaja.view.bicevida.cl/PlanillaCajaWS/getUrlPDFResponse")
    @RequestWrapper(localName = "getUrlPDF", targetNamespace = "http://ws.planillacaja.view.bicevida.cl/", className = "cl.bicevida.view.planillacaja.ws.GetUrlPDF")
    @ResponseWrapper(localName = "getUrlPDFResponse", targetNamespace = "http://ws.planillacaja.view.bicevida.cl/", className = "cl.bicevida.view.planillacaja.ws.GetUrlPDFResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cl.bicevida.view.planillacaja.ws.DatoPDFResponse getUrlPDF(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.String rut
    );
}
