package cl.bicevida.view.planillacaja.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630262
 * 2017-09-28T11:36:19.855-03:00
 * Generated source version: 3.1.5.redhat-630262
 * 
 */
@WebServiceClient(name = "PlanillaCajaWSService", 
                  wsdlLocation = "file:/C:/Users/gustavo.riquelmeg/workspace/bv-boton-pago-prima/src/main/resources/wsdl/PlanillaCajaWSPort.wsdl",
                  targetNamespace = "http://ws.planillacaja.view.bicevida.cl/") 
public class PlanillaCajaWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.planillacaja.view.bicevida.cl/", "PlanillaCajaWSService");
    public final static QName PlanillaCajaWSPort = new QName("http://ws.planillacaja.view.bicevida.cl/", "PlanillaCajaWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/gustavo.riquelmeg/workspace/bv-boton-pago-prima/src/main/resources/wsdl/PlanillaCajaWSPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlanillaCajaWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/gustavo.riquelmeg/workspace/bv-boton-pago-prima/src/main/resources/wsdl/PlanillaCajaWSPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlanillaCajaWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlanillaCajaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanillaCajaWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns PlanillaCajaWS
     */
    @WebEndpoint(name = "PlanillaCajaWSPort")
    public PlanillaCajaWS getPlanillaCajaWSPort() {
        return super.getPort(PlanillaCajaWSPort, PlanillaCajaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanillaCajaWS
     */
    @WebEndpoint(name = "PlanillaCajaWSPort")
    public PlanillaCajaWS getPlanillaCajaWSPort(WebServiceFeature... features) {
        return super.getPort(PlanillaCajaWSPort, PlanillaCajaWS.class, features);
    }

}
